/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/card/card.vue')['default']
    CardEducation: typeof import('./views/card-education.vue')['default']
    CardPersonalAdvantage: typeof import('./views/card-personal-advantage.vue')['default']
    CardProfile: typeof import('./views/card-profile.vue')['default']
    CardProjects: typeof import('./views/card-projects.vue')['default']
    CardTitle: typeof import('./components/card/card-title.vue')['default']
    ListItem: typeof import('./components/list-item.vue')['default']
    ProgramItem: typeof import('./components/program-item.vue')['default']
    ProjectItem: typeof import('./components/project-item.vue')['default']
    Separator: typeof import('./components/separator.vue')['default']
    SvgIcon: typeof import('./components/svg-icon.vue')['default']
    VFooter: typeof import('./components/v-footer.vue')['default']
  }
}
